### ISSUE TITLE
怎样高亮显示一个代码块中的一行代码？

### ISSUE THREAD

**Issue by gaospecial** [cosname/rmarkdown-guide#10]
比如下面的两个代码块，第二块比第一块多了 `lib_dirs: libs` 一行，有没有办法给这一行突出显示？

```yaml
---
title: "Habits"
output:
  html_document:
    self_contained: false
---
```

```yaml
---
title: "Habits"
output:
  html_document:
    self_contained: false
    lib_dir: libs
---
```
